### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by phennessey** [jacobbubu/acb#1]
I am attempting to run this on my mac. I removed all but one acb file and renamed it "pastels.acb" to test this. It seems to be having trouble creating a directory "converted". Not sure why:

```
Errors in pastels Error: ENOENT: no such file or directory, open 'converted/pastels.json'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2170:35)
    at Object.<anonymous> (/Users/[username]/Downloads/acb-master/index.coffee:18:16)
    at Object.<anonymous> (/Users/[username]/Downloads/acb-master/index.coffee:1:38)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.CoffeeScript.run (/opt/homebrew/lib/node_modules/coffeescript/lib/coffeescript/index.js:67:23)
    at compileScript (/opt/homebrew/lib/node_modules/coffeescript/lib/coffeescript/command.js:285:29)
    at compilePath (/opt/homebrew/lib/node_modules/coffeescript/lib/coffeescript/command.js:237:14)
    at Object.exports.run (/opt/homebrew/lib/node_modules/coffeescript/lib/coffeescript/command.js:158:20)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/coffeescript/bin/coffee:22:45)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'converted/pastels.json'
} pastels.acb
```

**Comment by Schleipnir74** [comment]
just make the "converted" directory yourself before running the script

**Comment by phennessey** [comment]
Yup, I figured it out last year! Would be nice if the script created the necessary directories.
